### ISSUE TITLE
help with client side validation 

### ISSUE THREAD

**Issue by Pandahisham** [timseverien/Promin#11]
Thanks for this cool plug in , but i am a newbie at javascript , can you please give a short example of client  side validation . 

My first field is Name that is requires and must be alphaneumerical only
second field is an email , required

how to stop promin from proceeding to next step if the input values don't match the validation rules and show a error message.

Really sorry for bothering you with such trivial things , thanks in advance

**Comment by timseverien** [comment]
By returning false in the `change` event handler, you can prevent Promin from proceeding:

    $('.promin').promin({
      events: {
        change: function() {
          return false;
        }
      }
    })
