### ISSUE TITLE
add class to current <p>

### ISSUE THREAD

**Issue by hikups** [timseverien/Promin#14]
Hey , first of all, thanks for this amazing form.

Not really an issue, but here we go

I´m trying to figure out how to add a class to the current  < p > that is visible to add some text animations. I´m very new around jquery so not shure how to do this.

 I've tried , but can't figure out where to add the class so it only adds to the current visible <  p >

You seem to toggle the display block to hidden, but i've been looking in the script, and can't figure out where this is being set.

Could you show me in the right direction?

very appreciated!

**Comment by timseverien** [comment]
Yeah, you can use the `change` event to do something on every change. The browser should show and draw the element before applying the class though, so we’ll need a setTimeout/requestAnimationFrame to work around this. Anyway, here’s a fiddle: http://jsfiddle.net/5yqwmocs/

**Comment by hikups** [comment]
awesome! thanks, just what i needed.
