### ISSUE TITLE
Could you help me add the version tag?

### ISSUE THREAD

**Issue by nolsherry** [timseverien/Promin#16]
Hello @timseverien ,
I am the member of [cdnjs](https://github.com/cdnjs) project.
We want to host this library.
Please add the version tags into your project, thank you very much!

![image](https://cloud.githubusercontent.com/assets/8747900/18222175/d7bfd668-71c0-11e6-85a3-6d18a594919a.png)

cdnjs/cdnjs#8525

**Comment by timseverien** [comment]
This project isn’t maintained and hasn’t received updates for a long while, so I’m not sure if it’s worth the effort. I have added the tag regardless.

**Comment by nolsherry** [comment]
@timseverien, thanks for your help, is the license of library repository is `MIT` ?
